# Generated by Django 5.0.7 on 2024-07-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
